### ISSUE TITLE
Is this website（https://deep-vg-bench.herokuapp.com/） unavailable?

### ISSUE THREAD

**Issue by wpumain** [gmberton/deep-visual-geo-localization-benchmark#11] opened 2023-02-24 05:53 UTC
Is this website（https://deep-vg-bench.herokuapp.com/） unavailable?
It is a great work,but unfortunately I can't open this website

**Comment by gmberton** [comment] 2023-02-26 20:52
Duplicate of #8

**Closed as completed by gmberton** 2023-02-26 20:52 UTC

**Comment by wpumain** [comment] 2023-02-27 05:52
Think you for your reply
